@startuml
hide empty description

' Hack: transparent exitPoints are used to model local transitions from composite states.
' Even if arrows are drawn as re-entering a state, external transitions are not used in this model (as in the QP framework).
skinparam state {
BackgroundColor<<exitPoint>> Transparent
BorderColor<<exitPoint>> Transparent
FontColor<<exitPoint>> Transparent
}

[*] --> WAITING_FOR_MODULES_INIT

WAITING_FOR_MODULES_INIT : FOTA_MODULE_READY / \n\t modules_ready.fota_ready = true;\n\t check_modules_ready();
WAITING_FOR_MODULES_INIT : POWER_MODULE_READY / \n\t modules_ready.power_ready = true;\n\t check_modules_ready();
WAITING_FOR_MODULES_INIT : LOCATION_MODULE_READY / \n\t modules_ready.location_ready = true;\n\t check_modules_ready();
WAITING_FOR_MODULES_INIT --> RUNNING : MAIN_MODULES_READY
state WAITING_FOR_MODULES_INIT

RUNNING : entry / \n\t timer_send_data_start(update_interval_sec);\n\t sync_start_time = k_uptime_seconds();
RUNNING : exit / \n\t timer_sample_stop();\n\t timer_send_data_stop();
RUNNING -> FOTA : FOTA_DOWNLOADING_UPDATE
RUNNING : CLOUD_PROVISIONED / cloud_synced_on_connect = false;
state RUNNING {
    [*] --> DISCONNECTED

    DISCONNECTED : entry / running_history = STATE_DISCONNECTED;
    DISCONNECTED --> CONNECTED : CLOUD_CONNECTED
    DISCONNECTED : TIMER_EXPIRED_CLOUD / \n\t timer_send_data_start(update_interval_sec);\n\t sync_start_time = k_uptime_seconds();
    DISCONNECTED : BUTTON_PRESS_LONG / ;
    DISCONNECTED : STORAGE_THRESHOLD_REACHED / ;
    state DISCONNECTED {
        [*] --> DISCONNECTED_WAITING

        DISCONNECTED_SAMPLING : entry / \n\t publish LED_RGB_SET(blink blue 10 times) \n\t sample_start_time = k_uptime_seconds(); \n\t publish POWER_BATTERY_PERCENTAGE_SAMPLE_REQUEST [CONFIG_APP_POWER] \n\t publish ENVIRONMENTAL_SENSOR_SAMPLE_REQUEST [CONFIG_APP_ENVIRONMENTAL] \n\t publish LOCATION_SEARCH_TRIGGER
        DISCONNECTED_SAMPLING --> DISCONNECTED_WAITING : LOCATION_SEARCH_DONE
        DISCONNECTED_SAMPLING : BUTTON_PRESS_SHORT / ;
        state DISCONNECTED_SAMPLING

        DISCONNECTED_WAITING : entry / \n\t waiting_entry_common(); (schedule next sample/cloud sync) \n\t publish LED_RGB_SET(blink red 10 times)
        DISCONNECTED_WAITING : exit / timer_sample_stop();
        DISCONNECTED_WAITING --> DISCONNECTED_SAMPLING : TIMER_EXPIRED_SAMPLE_DATA
        DISCONNECTED_WAITING -u-> DISCONNECTED_WAITING : TIMER_CONFIG_CHANGED
        DISCONNECTED_WAITING --> DISCONNECTED_SAMPLING : BUTTON_PRESS_SHORT
        state DISCONNECTED_WAITING
    }

    CONNECTED : entry [cloud_synced_on_connect == false] / \n\t running_history = STATE_CONNECTED; \n\t publish CLOUD_SHADOW_UPDATE_REPORTED_DEVICE \n\t publish FOTA_POLL_REQUEST \n\t publish CLOUD_SHADOW_GET_DESIRED \n\t cloud_synced_on_connect = true;
    CONNECTED : entry [else] / \n\t running_history = STATE_CONNECTED;
    CONNECTED --> DISCONNECTED : CLOUD_DISCONNECTED
    CONNECTED : CLOUD_SHADOW_RESPONSE_DESIRED \n|| CLOUD_SHADOW_RESPONSE_DELTA \n|| CLOUD_SHADOW_RESPONSE_EMPTY_DELTA \n|| CLOUD_SHADOW_RESPONSE_EMPTY_DESIRED / \n\t handle_cloud_shadow_response();
    CONNECTED_x1 -> CONNECTED_SENDING : TIMER_EXPIRED_CLOUD \n|| BUTTON_PRESS_LONG \n|| STORAGE_THRESHOLD_REACHED
    state CONNECTED {
        state CONNECTED_x1 <<exitPoint>>
        [*] --> CONNECTED_SENDING

        CONNECTED_SAMPLING : entry / \n\t publish LED_RGB_SET(blink blue 10 times) \n\t sample_start_time = k_uptime_seconds(); \n\t publish POWER_BATTERY_PERCENTAGE_SAMPLE_REQUEST [CONFIG_APP_POWER] \n\t publish ENVIRONMENTAL_SENSOR_SAMPLE_REQUEST [CONFIG_APP_ENVIRONMENTAL] \n\t publish LOCATION_SEARCH_TRIGGER
        CONNECTED_SAMPLING --> CONNECTED_WAITING : LOCATION_SEARCH_DONE
        CONNECTED_SAMPLING : BUTTON_PRESS_SHORT / ;
        CONNECTED_SAMPLING : STORAGE_THRESHOLD_REACHED / ;
        state CONNECTED_SAMPLING

        CONNECTED_WAITING : entry / waiting_entry_common(); (schedule next sample/cloud sync)
        CONNECTED_WAITING : exit / timer_sample_stop();
        CONNECTED_WAITING --> CONNECTED_SAMPLING : TIMER_EXPIRED_SAMPLE_DATA \n|| BUTTON_PRESS_SHORT
        CONNECTED_WAITING -u-> CONNECTED_WAITING : TIMER_CONFIG_CHANGED
        state CONNECTED_WAITING

        CONNECTED_SENDING : entry / \n\t cloud_send_now(); (Send stored data now, poll cloud/FOTA, and restart cloud send timer) \n\t publish LED_RGB_SET(blink green 10 times)
        CONNECTED_SENDING : STORAGE_THRESHOLD_REACHED / ;
        CONNECTED_SENDING --> CONNECTED_WAITING : STORAGE_BATCH_CLOSE
        state CONNECTED_SENDING
    }

}

FOTA : entry / publish LED_RGB_SET(blink purple indefinitely)
FOTA --> c4 : FOTA_DOWNLOAD_CANCELED \n|| FOTA_DOWNLOAD_REJECTED \n|| FOTA_DOWNLOAD_TIMED_OUT \n|| FOTA_DOWNLOAD_FAILED
state c4 <<choice>>
' Does not handle the hypothetical running_history=0 case.
c4 --> CONNECTED : [running_history == STATE_CONNECTED]
c4 --> DISCONNECTED : [running_history == STATE_DISCONNECTED]
FOTA : CLOUD_DISCONNECTED [running_history == STATE_CONNECTED] / running_history = STATE_DISCONNECTED;
FOTA : CLOUD_CONNECTED [running_history == STATE_DISCONNECTED] / running_history = STATE_CONNECTED;
state FOTA {
    [*] --> FOTA_DOWNLOADING

    FOTA_DOWNLOADING --> FOTA_WAITING_FOR_NETWORK_DISCONNECT : FOTA_SUCCESS_REBOOT_NEEDED
    FOTA_DOWNLOADING --> FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE : FOTA_IMAGE_APPLY_NEEDED
    state FOTA_DOWNLOADING

    FOTA_WAITING_FOR_NETWORK_DISCONNECT : entry / publish NETWORK_DISCONNECT
    FOTA_WAITING_FOR_NETWORK_DISCONNECT --> FOTA_REBOOTING : NETWORK_DISCONNECTED
    state FOTA_WAITING_FOR_NETWORK_DISCONNECT

    FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE: entry / \n\t publish NETWORK_DISCONNECT
    FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE --> FOTA_APPLYING_IMAGE : NETWORK_DISCONNECTED
    state FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE

    FOTA_APPLYING_IMAGE : entry / publish FOTA_IMAGE_APPLY
    FOTA_APPLYING_IMAGE --> FOTA_REBOOTING : FOTA_SUCCESS_REBOOT_NEEDED
    state FOTA_APPLYING_IMAGE

    FOTA_REBOOTING : entry / \n\t publish STORAGE_CLEAR \n\t LOG_WRN("Rebooting the device to apply the FOTA update"); \n\t LOG_PANIC(); \n\t k_sleep(K_SECONDS(10)); \n\t sys_reboot(SYS_REBOOT_COLD);
    state FOTA_REBOOTING

}

@enduml
